CREATE OR REPLACE EXTERNAL TABLE ${dataset_name_source}.source_phl_real_estate_transfers (
    cartodb_id INT64,
    the_geom STRING,
    the_geom_webmercator STRING,
    objectid INT64,
    document_id INT64,
    document_type STRING,
    display_date STRING,
    street_address STRING,
    zip_code STRING,
    ward STRING,
    grantors STRING,
    grantees STRING,
    cash_consideration FLOAT64,
    other_consideration FLOAT64,
    total_consideration FLOAT64,
    assessed_value FLOAT64,
    common_level_ratio FLOAT64,
    fair_market_value FLOAT64,
    state_tax_amount FLOAT64,
    state_tax_percent FLOAT64,
    local_tax_amount FLOAT64,
    local_tax_percent FLOAT64,
    adjusted_cash_consideration FLOAT64,
    adjusted_other_consideration FLOAT64,
    adjusted_total_consideration FLOAT64,
    adjusted_assessed_value FLOAT64,
    adjusted_fair_market_value FLOAT64,
    adjusted_state_tax_amount FLOAT64,
    adjusted_local_tax_amount FLOAT64,
    receipt_num STRING,
    receipt_date STRING,
    recording_date STRING,
    document_date STRING,
    condo_name STRING,
    unit_num STRING,
    address_low FLOAT64,
    address_low_suffix STRING,
    address_low_frac STRING,
    address_high STRING,
    street_predir STRING,
    street_name STRING,
    street_suffix STRING,
    street_postdir STRING,
    reg_map_id STRING,
    matched_regmap STRING,
    opa_account_num STRING,
    legal_remarks STRING,
    discrepancy STRING,
    property_count INT64,
    record_id STRING
)
OPTIONS (
    format = "PARQUET",
    uris = ['gs://${bucket_name}/real_estate_transfers/real_estate_transfers.parquet']
)
