main:
    params: [input]
    steps:
    - extract-phl-real-estate-transfers:
        call: http.post
        args:
            url: 'https://us-central1-musa5090s26-team3.cloudfunctions.net/extract_phl_real_estate_transfers'
            auth:
                type: OIDC
    - load-source-phl-real-estate-transfers:
        call: http.get
        args:
            url: 'https://us-central1-musa5090s26-team3.cloudfunctions.net/run_sql'
            query:
                sql: 'source_real_estate_transfers.sql'
            auth:
                type: OIDC
    - load-core-phl-real-estate-transfers:
        call: http.get
        args:
            url: 'https://us-central1-musa5090s26-team3.cloudfunctions.net/run_sql'
            query:
                sql: 'core_real_estate_transfers.sql'
            auth:
                type: OIDC