main:
    params: [input]
    steps:
    - extract-phl-pwd-parcels:
        call: http.post
        args:
            url: 'https://us-central1-musa5090s26-team3.cloudfunctions.net/extract_phl_pwd_parcels'
            auth:
                type: OIDC
    - load-source-phl-pwd-parcels:
        call: http.get
        args:
            url: 'https://us-central1-musa5090s26-team3.cloudfunctions.net/run_sql'
            query:
                sql: 'source_pwd_parcels.sql'
            auth:
                type: OIDC
    - load-core-phl-pwd-parcels:
        call: http.get
        args:
            url: 'https://us-central1-musa5090s26-team3.cloudfunctions.net/run_sql'
            query:
                sql: 'core_pwd_parcels.sql'
            auth:
                type: OIDC